### PR TITLE
For loop

### PR DESCRIPTION
**Pull request by Arifshariar7**
## PR Type

Feature

## PR Checklist

- [X] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made.
- [ ] Version number has been updated.
- [ ] Required modules have been added to respective "requirements*.txt" files.
- [ ] Relevant Test Cases added to this description (below).
- [ ] (Team) Label with affected action categories and semver status.

## Test Cases
- [TEST-0000](https://zeuz.zeuz.ai/Home/ManageTestCases/Edit/TEST-0000/)

### CODE REVIEW

**Comment by sazid** [comment]
@Muntasib-creator does this PR contain any breaking change?

**Review by sazid — CHANGES_REQUESTED** [review]
@Muntasib-creator does this PR contain any breaking change?
I don't see any changelog/version entries.

**Comment by Muntasib-creator** [comment]
> @Muntasib-creator does this PR contain any breaking change? I don't see any changelog/version entries.

@sazid There is no breaking change in this PR. if anything breaks thats a bug and no one reported any bug yet for for_loop_action

**Review by sazid — APPROVED** [review]

**Comment by sazid** [comment]
@Muntasib-creator merge this.

**Pull request merged**
